#!/bin/bash

set -e
cd "$(dirname "$0")"

script_dir="$(realpath "$PWD")"
base_dir="$(realpath "${script_dir}/../")"
pkgbuilds_dir="${base_dir}/pkgbuilds"

echo "==> Setting up database directory"
dbdir="${pkgbuilds_dir}/db"
mkdir -p "$dbdir"

echo "==> Compressing and copying packages"
builddir="${pkgbuilds_dir}/build"
(
  cd "$builddir"
  for pkg in *.pkg.tar; do
    echo "Compressing $pkg"
    zstd -o "$dbdir/$pkg.zst" "$pkg"
  done
)

echo "==> Setting up a package database"
repo-add "$dbdir/marcoolsink.db.tar.gz" "$dbdir"/*.pkg.tar.*
echo "  Here is the dbdir list:"
ls -la $dbdir

echo "==> Replacing symlinks"
(
  cd "$dbdir"
  for file in *.db *.files; do
    link="$(readlink "$file")"
    echo "  Running: \"cp --remove-destination \"$link\" \"$file\"\""
    cp --remove-destination "$link" "$file"
  done
)
